package com.revpeek.output;

import com.revpeek.analytics.AnalyticsService;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.stream.Collectors;

public class MarkdownRenderer {
    
    public String render(AnalyticsService.CommitStats stats) {
        StringBuilder markdown = new StringBuilder();
        
        markdown.append("# RevPeek Analytics Report\n\n");
        
        // Summary
        markdown.append("## Summary\n\n");
        markdown.append("- **Total Commits**: " + stats.totalCommits + "\n");
        markdown.append("- **Contributors**: " + stats.authorCommits.size() + "\n");
        markdown.append("- **First Commit**: " + (stats.firstCommitDate != null ? stats.firstCommitDate : "N/A") + "\n");
        markdown.append("- **Last Commit**: " + (stats.lastCommitDate != null ? stats.lastCommitDate : "N/A") + "\n\n");
        
        // Top Authors
        markdown.append("## Top Authors\n\n");
        markdown.append("| Author | Commits | Activity |\n");
        markdown.append("|--------|---------|----------|\n");
        
        // Sort authors by commit count
        Map<String, Integer> sortedAuthors = stats.authorCommits.entrySet()
            .stream()
            .sorted((e1, e2) -> e2.getValue().compareTo(e1.getValue()))
            .collect(Collectors.toMap(
                Map.Entry::getKey,
                Map.Entry::getValue,
                (e1, e2) -> e1,
                LinkedHashMap::new
            ));
        
        int maxCommits = stats.authorCommits.values().stream().mapToInt(Integer::intValue).max().orElse(1);
        for (Map.Entry<String, Integer> entry : sortedAuthors.entrySet()) {
            int barLength = Math.max(1, (entry.getValue() * 20) / maxCommits);
            StringBuilder bar = new StringBuilder();
            for (int i = 0; i < barLength; i++) {
                bar.append("#");
            }
            markdown.append("| " + escapeMarkdown(entry.getKey()) + " | " + entry.getValue() + " | " + bar.toString() + " |\n");
        }
        
        markdown.append("\n");
        
        // File Types
        markdown.append("## File Types\n\n");
        markdown.append("| File Type | Files | Distribution |\n");
        markdown.append("|-----------|-------|--------------|\n");
        
        // Sort file types by count
        Map<String, Integer> sortedFileTypes = stats.fileTypeDistribution.entrySet()
            .stream()
            .sorted((e1, e2) -> e2.getValue().compareTo(e1.getValue()))
            .collect(Collectors.toMap(
                Map.Entry::getKey,
                Map.Entry::getValue,
                (e1, e2) -> e1,
                LinkedHashMap::new
            ));
        
        int maxFiles = stats.fileTypeDistribution.values().stream().mapToInt(Integer::intValue).max().orElse(1);
        for (Map.Entry<String, Integer> entry : sortedFileTypes.entrySet()) {
            int barLength = Math.max(1, (entry.getValue() * 20) / maxFiles);
            StringBuilder bar = new StringBuilder();
            for (int i = 0; i < barLength; i++) {
                bar.append("#");
            }
            markdown.append("| " + escapeMarkdown(entry.getKey()) + " | " + entry.getValue() + " | " + bar.toString() + " |\n");
        }
        
        markdown.append("\n");
        markdown.append("---\n");
        markdown.append("*Generated by RevPeek - A terminal-first Git analytics CLI tool*\n");
        
        return markdown.toString();
    }
    
    private String escapeMarkdown(String input) {
        if (input == null) return "";
        return input.replace("|", "\\|");
    }
}